# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 178bf3b445b9d4f5fd78f34368a45f9260f660bcc539c46a935bbfb4e743da25139115ba9aad8ef66b80ee7d7dc362686a9430f4554940b15cb06933d6677ffb

test:
  secret_key_base: 04dd5919ccbd95166fb3986c8dfff12f122068409ba880eb4302f967b42c9e080efdadf37492941296a9fe17f0d59e690c77d8a49f6a16478cb762e69572294d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
